language: android

addons:
  apt:
    packages:
      - w3m

env:
  global:
    - ANDROID_TARGET=android-22
    - ANDROID_ABI=armeabi-v7a
    - ADB_INSTALL_TIMEOUT=12 # in minutes

jdk:
  # - openjdk8 # not yet available
  - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.1
    - extra-google-m2repository
    - extra-android-m2repository
    - ${ANDROID_TARGET}
    - android-25
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-audio -no-window -no-boot-anim &
  - android-wait-for-emulator

script:
  - ./gradlew clean check connectedCheck jacocoTestReport --stacktrace

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - echo '*** Connected Test Rsults ***'
  - w3m -dump ${TRAVIS_BUILD_DIR}/app/build/reports/androidTests/connected/*Test.html

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
